version: '3'
services:
  db:
    container_name: mysql
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

  foodlisa:
    container_name: foodlisa
    image: lisa/foodlisa:1.2
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ~/code/foodlisa/app:/app:delegated
    links:
      - db
    # stdin_open: true # -i
    # tty: true        # -t
